language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_16b1459e69da_key -iv $encrypted_16b1459e69da_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "dengxit"
- git config --global user.email dengxit@gmail.com
- npm install hexo@beta -g
- git clone https://github.com/dengxit/dengxit.github.io .deploy
script:
- hexo generate
- hexo deploy
branches:
  only:
  - master
