language: node_js
node_js:
  - stable

branches:
  only:
    - master

before_install:
  - git config --global user.name "dengxit"
  - git config --global user.email "dengxit@gmail.com"
  - sed -i'' "s~https://github.com/dengxit/hexoblog.git~https://${GH_TOKEN}@github.com/dengxit/hexoblog.git~" _config.yml

install:
  - npm install hexo-cli -g
  - npm install

script:
  - npm run deploy