language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "dengxit"
  - git config user.email "dengxit@github.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:travis-ci

branches:
  only:
    - travis-ci

global:
   - GH_REF: github.com:dengxit/dengxit.github.io.git